### ISSUE TITLE
Add BeeBrain Brushless to Betaflight board list

### ISSUE THREAD

**Issue by mattiasduerrmeier** [newbeedrone/BeeBrain-Brushless#1]
The BeeBrain Brushless board is not avalaible in the 'Update Firmware' tab of Betaflight.

Could you add the Beebrain Brushless Flight Controller to the Betaflight board list? This would make it much simpler to flash the correct firmware, especially for beginners.

**Comment by icemanx** [comment]
Hi @mattiasduerrmeier , our custom code prevents us to use the default code-base of Betaflight. I also strongly agree that it is the best and cleaner way for everyone. But the fact is, we have a custom target (osd code and beesign drivers). So, currently, there are no plans for this improvement. Thank you for your feedback!

**Comment by illmillrig** [comment]
I wish I had known this before buying a beebrain brushless.
