### ISSUE TITLE
betaflight 4.2 target 

### ISSUE THREAD

**Issue by illmillrig** [newbeedrone/BeeBrain-Brushless#2]
can we please get a betaflight 4.2 target?

**Comment by icemanx** [comment]
@illmillrig , we don't have a tuned firmware yet. When we have, it will be posted here first. Meantime you can check out the development branch. It's located at https://github.com/newbeedrone/betaflight/tree/beebrainBL_4.2.x-dev

**Comment by illmillrig** [comment]
Hi, Thanks!

Is there a 4.2 hex file for the beebrain brushless that I can flash to?  I don't see it anywhere.

In all honestly, I don't use the newbeedrone tune for 4.1. I didn't think it flew very good, and I think it's really too bad that you prevent people who don't use your tune from updating to 4.2 as early as they want to. 

Please get newbeedrone boards added to the targets list in betaflight, and allow people to update immediately without waiting for your 'tune'.
